name: CI

env:
  IMAGE_NAME: aunnk/my-go-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build . -t ${{ env.IMAGE_NAME }}:${GITHUB_SHA::7} -t ${{ env.IMAGE_NAME }}:latest
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}
